# Generated by Django 5.1.4 on 2025-01-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, default='no description', null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='power_in_watts',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
