# Generated by Django 5.1.4 on 2025-01-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0002_device_description_alter_device_power_in_watts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='power_in_watts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
    ]
