# Generated by Django 5.1.4 on 2025-01-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0003_alter_device_power_in_watts_alter_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, default='no description', max_length=400, null=True),
        ),
    ]
