# Generated by Django 5.1.4 on 2025-01-16 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0005_alter_device_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_timestamp', models.DateTimeField(auto_now_add=True)),
                ('power_in_watts', models.IntegerField()),
                ('off_timestamp', models.DateTimeField()),
                ('time_in_seconds', models.IntegerField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SmartHomeApp.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
