# Generated by Django 5.1.4 on 2025-01-16 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0006_logrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrow',
            old_name='user',
            new_name='owner',
        ),
    ]
