# Generated by Django 5.1.4 on 2025-01-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0007_rename_user_logrow_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrow',
            name='off_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logrow',
            name='power_in_watts',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
