# Generated by Django 5.1.4 on 2025-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHomeApp', '0008_alter_logrow_off_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrow',
            name='off_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
