# Generated by Django 5.1.4 on 2025-01-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_device_topic_remove_device_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='funcions',
            new_name='functions',
        ),
    ]
